
version: "3.9"

services:
  frontend:
    build: ./frontend
    container_name: shop_frontend
    ports:
      - "8000:8000"
    depends_on:
      - users
      - products
      - orders
      - inventory
      - payments
      - notifications

  users:
    build: ./users_service
    container_name: users_service
    ports:
      - "8001:8000"

  products:
    build: ./products_service
    container_name: products_service
    ports:
      - "8002:8000"

  orders:
    build: ./orders_service
    container_name: orders_service
    ports:
      - "8003:8000"

  inventory:
    build: ./inventory_service
    container_name: inventory_service
    ports:
      - "8004:8000"

  payments:
    build: ./payments_service
    container_name: payments_service
    ports:
      - "8005:8000"

  notifications:
    build: ./notifications_service
    container_name: notifications_service
    ports:
      - "8006:8000"
