name: Build and Test Microservices

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies for all services
        run: |
          pip install --upgrade pip
          pip install -r users_service/requirements.txt
          pip install -r products_service/requirements.txt
          pip install -r orders_service/requirements.txt
          pip install -r inventory_service/requirements.txt
          pip install -r payments_service/requirements.txt
          pip install -r notifications_service/requirements.txt

      # ---- ВОТ ЭТИ ШАГИ ГЛАВНЫЕ ----

      - name: Run users_service tests
        working-directory: users_service
        run: pytest

      - name: Run products_service tests
        working-directory: products_service
        run: pytest

      - name: Run orders_service tests
        working-directory: orders_service
        run: pytest

      - name: Run inventory_service tests
        working-directory: inventory_service
        run: pytest

      - name: Run payments_service tests
        working-directory: payments_service
        run: pytest

      - name: Run notifications_service tests
        working-directory: notifications_service
        run: pytest
