name: CI Pipeline

on:
  push:
  pull_request:

jobs:
  tests:
    name: Run unit tests for all microservices
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies for tests
        run: |
          pip install --upgrade pip
          pip install -r users_service/requirements.txt
          pip install -r products_service/requirements.txt
          pip install -r orders_service/requirements.txt
          pip install -r inventory_service/requirements.txt
          pip install -r payments_service/requirements.txt
          pip install -r notifications_service/requirements.txt

      - name: Run users_service tests
        working-directory: users_service
        run: pytest

      - name: Run products_service tests
        working-directory: products_service
        run: pytest

      - name: Run orders_service tests
        working-directory: orders_service
        run: pytest

      - name: Run inventory_service tests
        working-directory: inventory_service
        run: pytest

      - name: Run payments_service tests
        working-directory: payments_service
        run: pytest

      - name: Run notifications_service tests
        working-directory: notifications_service
        run: pytest


  build:
    name: Build Docker images
    runs-on: ubuntu-latest
    needs: tests     # билд запускается только если тесты прошли

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Users Service
        run: docker build -t users_service:latest users_service/

      - name: Build Products Service
        run: docker build -t products_service:latest products_service/

      - name: Build Orders Service
        run: docker build -t orders_service:latest orders_service/

      - name: Build Inventory Service
        run: docker build -t inventory_service:latest inventory_service/

      - name: Build Payments Service
        run: docker build -t payments_service:latest payments_service/

      - name: Build Notifications Service
        run: docker build -t notifications_service:latest notifications_service/
